### ISSUE TITLE
No way to customize this?

### ISSUE THREAD

**Issue by bramhechatejas** [diegoddox/react-redux-toastr#247]
Hello,

We wanted to customize this based on different params such as font-family, size, colours etc. Is there a way to do so? I have tried going through docs, but nowhere I found this information. Minor customizations are always needed. Could you please direct us?

**Comment by diegoddox** [comment]
Just override the CSS with your own rules

**Comment by EmWa94** [comment]
Hi,
how override it? When I'm trying override any class my class are higher in CSS hierarchy than defaults. The only way is using !important, but this way is rather improper solution.

**Comment by GokulSNarayan** [comment]
Go to this file  **node_modules/react-redux-toastr/src/styles/index.scss'**  and customize as per your requirement

**Comment by getanwar** [comment]
> Go to this file **node_modules/react-redux-toastr/src/styles/index.scss'** and customize as per your requirement

One should remember that if you customize any file inside `node_modules/` next `npm install` or updating the package will remove your customization! Instead overwrite the css rules on your own `css`/`scss` file.

**Comment by getanwar** [comment]
> Hi,
> how override it? When I'm trying override any class my class are higher in CSS hierarchy than defaults. The only way is using !important, but this way is rather improper solution.

Make sure that your styles come after package's styles. Otherwise, your styles will be overwritten by that of the package. I agree that it is an improper way, this could be done by leveraging CSS variable. But thanks to the lib author, the usage of redux for notification is cleaver here. I could use it from anywhere (components, thunk, redux-saga etc)

**Comment by getanwar** [comment]
If someone still needs help with overwriting default styles. Here is how I did it:

```scss
@import 'react-redux-toastr/src/styles/index';

.redux-toastr .toastr {
    &.rrt-error {
        background-color: var(--color-danger-500);
    }
    &.rrt-success {
        background-color: var(--color-success-500);
    }
    &.rrt-warning {
        background-color: var(--color-warning-500);
    }
}

.redux-toastr .toastr .rrt-middle-container {
    font-family: var(--font-family);
}

.redux-toastr .toastr .close-toastr {
    opacity: 1;

    span {
        top: 20px;
        color: #fff;
    }
}
```
